dist: trusty
sudo: required
language: python
python:
  - '2.7'
services:
  - memcached
env:
  global:
    - ENV=test
    - PYTHONPATH="$TRAVIS_BUILD_DIR"
install:
    - cd build && bash ubuntu-install.sh && cd ..
script: make test
